In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
engine = create_engine(
    'mysql+pymysql://root:1111@localhost/film_dw'
)

In [3]:
pd.read_sql("SELECT * FROM Dim_Customer LIMIT 5;", engine)

,customer_key,customer_id,full_name,email,active_status,create_date
0,1,1,MARY SMITH,MARY.SMITH@sakilacustomer.org,1,2006-02-14
1,2,2,PATRICIA JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,1,2006-02-14
2,3,3,LINDA WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,1,2006-02-14
3,4,4,BARBARA JONES,BARBARA.JONES@sakilacustomer.org,1,2006-02-14
4,5,5,ELIZABETH BROWN,ELIZABETH.BROWN@sakilacustomer.org,1,2006-02-14

In [4]:
query1 = '''
SELECT
    f.title,
    SUM(fr.rental_count) AS total_rentals

FROM Fact_Rental fr

JOIN Dim_Film f
    ON fr.film_key = f.film_key

GROUP BY f.title

ORDER BY total_rentals DESC
LIMIT 10;
'''

In [5]:
df1 = pd.read_sql(query1, engine)

df1

                 title  total_rentals
0   BUCKET BROTHERHOOD          102.0
1       GRIT CLOCKWORK           99.0
2       FORWARD TEMPLE           99.0
3     ROCKETEER MOTHER           99.0
4  RIDGEMONT SUBMARINE           96.0
5        CAT CONEHEADS           96.0
6        SCALAWAG DUCK           96.0
7       JUGGLER HARDLY           96.0
8         NETWORK PEAK           93.0
9        APACHE DIVINE           93.0

In [6]:
query2 = '''
SELECT
    s.store_id,
    SUM(fp.payment_amount) AS total_revenue

FROM Fact_Payment fp

JOIN Dim_Store s
    ON fp.store_key = s.store_key

GROUP BY s.store_id

ORDER BY total_revenue DESC;
'''

In [7]:
df2 = pd.read_sql(query2, engine)

df2

   store_id  total_revenue
0         2      101760.66
1         1      101596.08

In [8]:
query3 = '''
SELECT
    c.full_name,
    SUM(fp.payment_amount) AS total_spent

FROM Fact_Payment fp

JOIN Dim_Customer c
    ON fp.customer_key = c.customer_key

GROUP BY c.full_name

ORDER BY total_spent DESC
LIMIT 10;
'''

In [9]:
df3 = pd.read_sql(query3, engine)

df3

        full_name  total_spent
0     CECIL VINES       694.44
1       KARL SEAL       664.65
2    ELEANOR HUNT       649.62
3  CLINTON BUFORD       622.50
4      CLARA SHAW       586.74
5  RHONDA KENNEDY       583.83
6   MARION SNYDER       583.83
7   SCOTT SHELLEY       568.50
8   TOMMY COLLAZO       559.86
9     WESLEY BULL       532.80

In [13]:
query4 = """
SELECT 
    d.year,
    d.month_name,
    SUM(fp.payment_amount) AS revenue
FROM fact_payment fp
JOIN dim_date d 
    ON fp.payment_date_key = d.date_key
GROUP BY d.year, d.month_name
ORDER BY d.year, d.month_name;
"""

df4 = pd.read_sql(query4, engine)
df4

   year month_name   revenue
0  2005     August  72596.49
1  2005       July  85528.44
2  2005       June  29108.22
3  2005        May  14539.17
4  2006   February   1584.42

In [14]:
query5 = '''
SELECT
    f.title,
    AVG(fr.late_return_days) AS avg_late_days

FROM fact_rental fr

JOIN dim_film f
    ON fr.film_key = f.film_key

GROUP BY f.title

ORDER BY avg_late_days DESC

LIMIT 10;
'''

df5 = pd.read_sql(query5, engine)

df5

                 title  avg_late_days
0      MOTHER OLEANDER         4.0000
1   MAGNIFICENT CHITTY         3.8750
2        HUSTLER PARTY         3.6818
3     TYCOON GATHERING         3.6667
4     TELEGRAPH VOYAGE         3.5926
5          RUN PACIFIC         3.5000
6  BACKLASH UNDEFEATED         3.4500
7     VIRTUAL SPOILERS         3.4286
8  LIBERTY MAGNIFICENT         3.3333
9         LOVER TRUMAN         3.3000

In [15]:
query6 = '''
SELECT
    l.city,
    SUM(fr.rental_count) AS total_rentals

FROM fact_rental fr

JOIN dim_location l
    ON fr.location_key = l.location_key

GROUP BY l.city

ORDER BY total_rentals DESC

LIMIT 10;
'''

df6 = pd.read_sql(query6, engine)

df6

               city  total_rentals
0            Aurora          300.0
1            London          288.0
2       Saint-Denis          138.0
3        Cape Coral          135.0
4             Tanza          126.0
5        Molodetšno          126.0
6          Changhwa          123.0
7  Ourense (Orense)          120.0
8         Changzhou          120.0
9         Apeldoorn          117.0

In [19]:
query7 = '''
SELECT
    s.full_name,
    SUM(fp.payment_amount) AS total_sales

FROM fact_payment fp

JOIN dim_staff s
    ON fp.staff_key = s.staff_key

GROUP BY s.full_name

ORDER BY total_sales DESC;
'''

df7 = pd.read_sql(query7, engine)

df7

      full_name  total_sales
0  Jon Stephens    102349.74
1  Mike Hillyer    101007.00