In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
engine = create_engine(
    'mysql+pymysql://root:1111@localhost/film_dw'
)

In [4]:
pd.read_sql("SELECT * FROM Dim_Customer LIMIT 5;", engine)

,customer_key,customer_id,full_name,email,active_status,create_date
0,1,1,MARY SMITH,MARY.SMITH@sakilacustomer.org,1,2006-02-14
1,2,2,PATRICIA JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,1,2006-02-14
2,3,3,LINDA WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,1,2006-02-14
3,4,4,BARBARA JONES,BARBARA.JONES@sakilacustomer.org,1,2006-02-14
4,5,5,ELIZABETH BROWN,ELIZABETH.BROWN@sakilacustomer.org,1,2006-02-14

In [6]:
query1 = '''
SELECT
    f.title,
    SUM(fr.rental_count) AS total_rentals

FROM Fact_Rental fr

JOIN Dim_Film f
    ON fr.film_key = f.film_key

GROUP BY f.title

ORDER BY total_rentals DESC
LIMIT 10;
'''

In [7]:
df1 = pd.read_sql(query1, engine)

df1

                 title  total_rentals
0   BUCKET BROTHERHOOD          102.0
1       GRIT CLOCKWORK           99.0
2       FORWARD TEMPLE           99.0
3     ROCKETEER MOTHER           99.0
4  RIDGEMONT SUBMARINE           96.0
5        CAT CONEHEADS           96.0
6        SCALAWAG DUCK           96.0
7       JUGGLER HARDLY           96.0
8         NETWORK PEAK           93.0
9        APACHE DIVINE           93.0

In [8]:
query2 = '''
SELECT
    s.store_id,
    SUM(fp.payment_amount) AS total_revenue

FROM Fact_Payment fp

JOIN Dim_Store s
    ON fp.store_key = s.store_key

GROUP BY s.store_id

ORDER BY total_revenue DESC;
'''

In [9]:
df2 = pd.read_sql(query2, engine)

df2

   store_id  total_revenue
0         2      101760.66
1         1      101596.08

In [10]:
query3 = '''
SELECT
    c.full_name,
    SUM(fp.payment_amount) AS total_spent

FROM Fact_Payment fp

JOIN Dim_Customer c
    ON fp.customer_key = c.customer_key

GROUP BY c.full_name

ORDER BY total_spent DESC
LIMIT 10;
'''

In [11]:
df3 = pd.read_sql(query3, engine)

df3

        full_name  total_spent
0     CECIL VINES       694.44
1       KARL SEAL       664.65
2    ELEANOR HUNT       649.62
3  CLINTON BUFORD       622.50
4      CLARA SHAW       586.74
5  RHONDA KENNEDY       583.83
6   MARION SNYDER       583.83
7   SCOTT SHELLEY       568.50
8   TOMMY COLLAZO       559.86
9     WESLEY BULL       532.80